server:
  port: 10000

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                     # 开启以注册中心服务名创建动态路由功能，从而可以用微服务名进行路由
      routes:
        - id: payment_routh1                # 路由ID，没有固定规则，要求唯一，建议配合服务名称命名
          # uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   # 匹配微服务名
          predicates:                       # 断言，路径匹配的进行路由
            - Path=/payment/get/**

        - id: payment_routh2
          # uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/loadBalance/**
#            - After=2020-06-13T01:19:05.653+08:00[Asia/Shanghai]
#            - Before=2020-06-13T01:21:05.653+08:00[Asia/Shanghai]
#            - Between=2020-06-13T01:19:05.653+08:00[Asia/Shanghai],2020-06-13T01:21:05.653+08:00[Asia/Shanghai]
#            - Cookie=username,joseph
#            - Header=X-Request-Id, \d+
#            - Host=**.somehost.org,**.anotherhost.org
#            - Method=GET,POST
#            - Query=foo

eureka:
  instance:
    hostname: GatewayService10000
    prefer-ip-address: true       # 访问地址显示IP
    # 每间隔1s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 1
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    # true表示要将自己注册进eureka server
    register-with-eureka: true
    # true表示从eureka server抓取自己的注册地址，单节点任意设置，多节点必须设置为true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
