server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://hdfs-host4:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    # true表示要将自己注册进eureka server
    register-with-eureka: true
    # true表示从eureka server抓取自己的注册地址，单节点任意设置，多节点必须设置为true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.joseph.cloud.entities

