server:
  port: 8004

spring:
  application:
    name: cloud-payment-hystrix-service

eureka:
  instance:
    instance-id: PaymentHystrixService8004
    prefer-ip-address: true       # 访问地址显示IP
    # 每间隔1s，向服务端发送一次心跳，证明自己依然"存活"
    lease-renewal-interval-in-seconds: 1
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    # true表示要将自己注册进eureka server
    register-with-eureka: true
    # true表示从eureka server抓取自己的注册地址，单节点任意设置，多节点必须设置为true才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka


