server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  server:
    # false/true 关闭/打开 自我保护机制，保证不可用服务及时踢出，测试关闭，线上打开
    enable-self-preservation: true
    # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 10000
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己就是注册中心，我的职责是维护服务实例，并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server交互的地址查询服务，注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
