server:
  port: 8101

spring:
  application:
    name: cloudalibaba-seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group     # 自定义事务组名称，跟seata-server的file.conf配置中保持一致
    nacos:
      discovery:
        server-addr: hdfs-host1:8000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://hdfs-host4:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml


